### PR TITLE
Port to newer Xorg releases

### PR DESCRIPTION
**Pull request by shadeslayer**

### CODE REVIEW

**Review by mripard — CHANGES_REQUESTED** [review]
Hi,

It would make more sense if you merged the patches one by one, which seems to be:
https://github.com/endlessm/xf86-video-armsoc/commit/a97ceb3bac8bcf53bf4ea3db0a2c8921d8017ef8

And
https://github.com/endlessm/xf86-video-armsoc/commit/787c57c915e3a66dc10f525e0a05c7af35262c7d
Both these patches should also carry your Signed-off-by in addition to the original ones.

Thanks!

**Comment by net147** [comment]
Already solved by https://github.com/mripard/xf86-video-armsoc/pull/5 so this is no longer needed.

**Comment by falsovsky** [comment]
You missed the commit to src/armsoc_exa.c
The project fails building because of format conversion.

**Comment by net147** [comment]
@falsovsky Can you create a pull request?

**Comment by falsovsky** [comment]
Done

**Pull request closed without merging**
